/**
 * lib/ai/dedup.ts
 *
 * Message-level and semantic event-level deduplication.
 *
 * Layered strategy (deterministic first, semantic second):
 *   1. Message fingerprinting — SHA-256 of (source + sender + normalizedContent)
 *      Timestamps are NOT required; included when available.
 *   2. Normalized event keys — order-independent topic words after synonym
 *      normalization. Type must match exactly; topic words use Jaccard similarity.
 *   3. Legitimate state changes — same event key + different status = state
 *      transition (both preserved, current state updated).
 */

import { createHash } from "crypto";
import type { Item, Conflict, Source, Status } from "@/lib/types";

// ============================================================================
// MESSAGE FINGERPRINTING
// ============================================================================

/**
 * Normalize text for fingerprinting: lowercase, collapse whitespace,
 * strip punctuation that varies across sources (e.g. line breaks, bullets).
 */
function normalizeContent(content: string): string {
  return content
    .toLowerCase()
    .replace(/[^\w\s]/g, " ")   // strip punctuation
    .replace(/\s+/g, " ")       // collapse whitespace
    .trim();
}

/**
 * Compute a deterministic fingerprint for a message within a project.
 *
 * Fields used (in order of availability):
 *   projectId + source + normalizedSender + normalizedContent [+ timestamp if present]
 *
 * Timestamp is included only when explicitly provided, so the same message
 * without a timestamp is still recognised as a duplicate across imports.
 */
export function fingerprintMessage(params: {
  projectId: string;
  source: Source;
  sender: string;
  content: string;
  /** ISO timestamp string — omit if unavailable / unreliable */
  timestamp?: string;
}): string {
  const parts = [
    params.projectId,
    params.source,
    params.sender.toLowerCase().trim(),
    normalizeContent(params.content),
  ];
  // Only include timestamp when it encodes real information (not just Date.now())
  if (params.timestamp && !isAutoGeneratedTimestamp(params.timestamp)) {
    parts.push(params.timestamp);
  }
  return createHash("sha256").update(parts.join("\u0000")).digest("hex").slice(0, 40);
}

/**
 * Detect timestamps we generate ourselves (Date.now() + i) — these carry no
 * real deduplication value and should be excluded from the fingerprint.
 */
function isAutoGeneratedTimestamp(ts: string): boolean {
  // If it's within 10 seconds of the current time it's almost certainly auto-generated
  const delta = Math.abs(Date.now() - new Date(ts).getTime());
  return delta < 10_000;
}

// ============================================================================
// SYNONYM + NORMALIZATION TABLE
// ============================================================================
// Domain-specific synonyms that should be treated as identical for event
// key purposes. Ordered from most specific to most general.

const SYNONYMS: [RegExp, string][] = [
  // Material options
  [/\boption[\s-]?b\b|\bsecond[\s-]?option\b|\bsecond[\s-]?marble\b|\bopt[\s-]?b\b/gi, "option_b"],
  [/\boption[\s-]?a\b|\bfirst[\s-]?option\b|\boriginal[\s-]?option\b|\boriginal[\s-]?marble\b/gi, "option_a"],
  [/\boption[\s-]?c\b|\bthird[\s-]?option\b/gi, "option_c"],
  // Materials
  [/\bkitchen\b/gi, "kitchen"],
  [/\bmarble\b|\bstone\b|\btile\b|\bmaterial\b/gi, "marble"],
  // Actions
  [/\binstallation\b|\binstall(ing|ed)?\b/gi, "installation"],
  [/\bapprove[ds]?\b|\bconfirm(ed|ing)?\b|\bselect(ed|ing)?\b|\bgo[\s-]ahead\b|\bproceed\b/gi, "approved"],
  [/\breject(ed|ing)?\b|\brefuse[ds]?\b|\bdo[\s-]not[\s-]want\b|\bnot[\s-]proceed\b/gi, "rejected"],
  [/\bhold\b|\bdelay(ed|ing)?\b|\bpause[ds]?\b|\bblock(ed|ing)?\b|\bstop\b|\bwait\b/gi, "blocked"],
  [/\bdeliver[y]?\b|\bdelivering\b|\bdelivered\b/gi, "delivery"],
  [/\bschedule[d]?\b|\btiming\b|\bstart[\s-]date\b/gi, "schedule"],
  // Roles
  [/\bclient\b|\bowner\b|\bpriya\b/gi, "client"],
  [/\barchitect\b|\baditi\b/gi, "architect"],
  [/\bcontractor\b|\brohan\b/gi, "contractor"],
  [/\bsupplier\b|\bvendor\b|\bstoneworks\b/gi, "supplier"],
];

// Words too generic to help with deduplication
const STOP_WORDS = new Set([
  "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
  "of", "with", "by", "from", "is", "was", "are", "were", "has", "have",
  "had", "be", "been", "being", "this", "that", "these", "those", "it",
  "its", "will", "would", "could", "should", "may", "might", "must",
  "please", "need", "want", "get", "put", "make", "take", "now", "then",
  "before", "after", "until", "once", "also", "still", "already", "yet",
  "new", "project", "communication", "message", "note", "update", "item",
]);

function applySynonyms(text: string): string {
  let normalized = text.toLowerCase();
  for (const [pattern, replacement] of SYNONYMS) {
    normalized = normalized.replace(pattern, replacement);
  }
  return normalized;
}

function extractTopicWords(text: string, maxWords = 5): string[] {
  const normalized = applySynonyms(text);
  const words = normalized
    .replace(/[^\w\s_]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .split(/\s+/)
    .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
  // Deduplicate and sort so order doesn't matter
  return [...new Set(words)].sort().slice(0, maxWords);
}

// ============================================================================
// EVENT KEY NORMALIZATION
// ============================================================================

export type ItemCategory =
  | "decision"
  | "action"
  | "blocker"
  | "risk"
  | "pending"
  | "update"
  | "deadline"
  | "conflict";

/**
 * Produce a normalized, order-independent event key from an item's type,
 * title, and description.
 *
 * Format: "<category>:<sorted_topic_word1>:<sorted_topic_word2>:..."
 *
 * Examples:
 *   normalizeEventKey("decision", "Option B marble approved", "Client chose Option B")
 *   → "decision:approved:marble:option_b"
 *
 *   normalizeEventKey("decision", "Client selected the second marble", "Second option selected")
 *   → "decision:approved:marble:option_b"   ← same key via synonym mapping
 */
export function normalizeEventKey(
  category: ItemCategory,
  title: string,
  description: string
): string {
  const combined = `${title} ${description}`;
  const topicWords = extractTopicWords(combined);
  return `${category}:${topicWords.join(":")}`;
}

// ============================================================================
// JACCARD SIMILARITY
// ============================================================================

/**
 * Topic-word Jaccard similarity between two event keys.
 * Returns 0 if categories differ (type must match exactly).
 * Returns 1.0 for identical keys.
 */
export function eventKeySimilarity(key1: string, key2: string): number {
  if (key1 === key2) return 1.0;

  const parts1 = key1.split(":");
  const parts2 = key2.split(":");

  // Category must match
  if (parts1[0] !== parts2[0]) return 0;

  const words1 = new Set(parts1.slice(1));
  const words2 = new Set(parts2.slice(1));

  if (words1.size === 0 && words2.size === 0) return 1.0;
  if (words1.size === 0 || words2.size === 0) return 0;

  const intersection = [...words1].filter((w) => words2.has(w)).length;
  const union = new Set([...words1, ...words2]).size;

  return intersection / union;
}

// ============================================================================
// EVENT DEDUPLICATION DECISION
// ============================================================================

/** Similarity threshold above which we consider two events the "same" event */
const SIMILARITY_THRESHOLD = 0.45;

export type DedupAction =
  | "create"        // Genuinely new event — insert it
  | "skip"          // Exact duplicate (same event, same status) — ignore
  | "state-change"  // Same event, status changed — update existing item + log change
  | "add-source";   // Same event, same status, new supporting message — link message

export type DedupResult = {
  action: DedupAction;
  existingIndex?: number; // Index into the `existing` array that matched
  reason: string;
  similarity: number;
};

/**
 * Decide what to do with a newly extracted event against a list of existing items.
 *
 * Decision logic:
 *   similarity >= threshold AND same status  → "skip" (or "add-source" if sourceMessageId differs)
 *   similarity >= threshold AND diff status  → "state-change"
 *   similarity < threshold                  → "create"
 */
export function decideDedupAction(
  newTitle: string,
  newDescription: string,
  newStatus: Status,
  newEventKey: string,
  existing: Item[]
): DedupResult {
  let bestSimilarity = 0;
  let bestIndex = -1;

  for (let i = 0; i < existing.length; i++) {
    const item = existing[i];
    const existKey =
      item.eventKey ?? normalizeEventKey("action", item.title, item.description);
    const sim = eventKeySimilarity(newEventKey, existKey);

    if (sim > bestSimilarity) {
      bestSimilarity = sim;
      bestIndex = i;
    }
  }

  if (bestSimilarity < SIMILARITY_THRESHOLD) {
    return { action: "create", reason: "No similar event found", similarity: bestSimilarity };
  }

  const matched = existing[bestIndex];

  if (matched.status === newStatus) {
    return {
      action: "add-source",
      existingIndex: bestIndex,
      reason: `Duplicate of "${matched.title}" (sim=${bestSimilarity.toFixed(2)})`,
      similarity: bestSimilarity,
    };
  }

  return {
    action: "state-change",
    existingIndex: bestIndex,
    reason: `Status change on "${matched.title}": ${matched.status} → ${newStatus} (sim=${bestSimilarity.toFixed(2)})`,
    similarity: bestSimilarity,
  };
}

// ============================================================================
// SMART ITEM MERGE
// ============================================================================

const uid = (prefix: string) =>
  `${prefix}_${Math.random().toString(36).slice(2, 9)}`;

export type MergeChange =
  | { type: "created"; item: Item }
  | { type: "state-change"; previous: Status; next: Status; item: Item }
  | { type: "source-added"; item: Item; messageId: string }
  | { type: "skipped"; reason: string };

/**
 * Merge a list of newly extracted items into an existing list with full
 * deduplication and state-change tracking.
 *
 * @param existing   Current items in this category from prior state
 * @param incoming   Newly extracted items from this import (Partial<Item>)
 * @param category   Item category ("decision", "blocker", etc.)
 * @param latestMsgId  ID of a representative message from this import batch
 * @returns  { merged: Item[], mergeChanges: MergeChange[] }
 */
export function smartMergeItems(
  existing: Item[],
  incoming: Partial<Item>[],
  category: ItemCategory,
  latestMsgId: string
): { merged: Item[]; mergeChanges: MergeChange[] } {
  const merged: Item[] = existing.map((x) => ({ ...x }));
  const mergeChanges: MergeChange[] = [];

  for (const raw of incoming) {
    if (!raw.title?.trim()) continue;

    const title = raw.title.trim();
    const description = raw.description?.trim() ?? "";
    const status = (raw.status ?? "open") as Status;
    const eventKey = raw.eventKey ?? normalizeEventKey(category, title, description);

    const decision = decideDedupAction(title, description, status, eventKey, merged);

    if (decision.action === "create") {
      const newItem: Item = {
        id: uid(category),
        title,
        description,
        status,
        priority: (raw.priority ?? "medium") as "low" | "medium" | "high",
        owner: raw.owner,
        source: (raw.source ?? "whatsapp") as Source,
        sourceMessageId: raw.sourceMessageId ?? latestMsgId,
        sourceMessageIds: [raw.sourceMessageId ?? latestMsgId],
        timestamp: new Date().toISOString(),
        relatedTopics: raw.relatedTopics ?? [],
        dependencies: raw.dependencies ?? [],
        eventKey,
      };
      merged.push(newItem);
      mergeChanges.push({ type: "created", item: newItem });
      console.log(`[Dedup] CREATE ${category}: "${title}"`);
    } else if (decision.action === "state-change" && decision.existingIndex !== undefined) {
      const prev = merged[decision.existingIndex];
      const previousStatus = prev.status;
      merged[decision.existingIndex] = {
        ...prev,
        status,
        description: description || prev.description,
        eventKey,
        sourceMessageIds: [
          ...(prev.sourceMessageIds ?? [prev.sourceMessageId]),
          latestMsgId,
        ],
      };
      mergeChanges.push({
        type: "state-change",
        previous: previousStatus,
        next: status,
        item: merged[decision.existingIndex],
      });
      console.log(`[Dedup] STATE-CHANGE ${category}: "${prev.title}" ${previousStatus}→${status}`);
    } else if (decision.action === "add-source" && decision.existingIndex !== undefined) {
      // Link the new message as an additional source reference
      const prev = merged[decision.existingIndex];
      const existing_sources = prev.sourceMessageIds ?? [prev.sourceMessageId];
      if (!existing_sources.includes(latestMsgId)) {
        merged[decision.existingIndex] = {
          ...prev,
          sourceMessageIds: [...existing_sources, latestMsgId],
        };
        mergeChanges.push({
          type: "source-added",
          item: merged[decision.existingIndex],
          messageId: latestMsgId,
        });
        console.log(`[Dedup] ADD-SOURCE ${category}: "${prev.title}" ← msg ${latestMsgId}`);
      } else {
        mergeChanges.push({ type: "skipped", reason: decision.reason });
        console.log(`[Dedup] SKIP ${category}: "${title}" — ${decision.reason}`);
      }
    } else {
      mergeChanges.push({ type: "skipped", reason: decision.reason });
      console.log(`[Dedup] SKIP ${category}: "${title}" — ${decision.reason}`);
    }
  }

  return { merged, mergeChanges };
}

// ============================================================================
// CONFLICT DEDUPLICATION
// ============================================================================

export function smartMergeConflicts(
  existing: Conflict[],
  incoming: Partial<Conflict>[]
): Conflict[] {
  const merged: Conflict[] = [...existing];

  for (const raw of incoming) {
    if (!raw.topic) continue;

    const normalizedTopic = applySynonyms(raw.topic).toLowerCase().trim();

    const existingMatch = merged.findIndex((c) => {
      const existTopic = applySynonyms(c.topic).toLowerCase().trim();
      const sim = eventKeySimilarity(
        `conflict:${extractTopicWords(normalizedTopic).join(":")}`,
        `conflict:${extractTopicWords(existTopic).join(":")}`
      );
      return sim >= SIMILARITY_THRESHOLD;
    });

    if (existingMatch >= 0) {
      // If the conflict was already resolved, don't re-open it
      if (merged[existingMatch].status === "resolved") {
        console.log(`[Dedup] SKIP conflict: "${raw.topic}" — already resolved`);
        continue;
      }
      // Update with latest information but preserve original
      merged[existingMatch] = {
        ...merged[existingMatch],
        recommendedAction: raw.recommendedAction ?? merged[existingMatch].recommendedAction,
      };
      console.log(`[Dedup] UPDATE conflict: "${raw.topic}"`);
    } else {
      merged.push({
        id: uid("conflict"),
        topic: raw.topic,
        status: (raw.status ?? "open") as Status,
        sideA: raw.sideA ?? { statement: "", owner: "", sourceMessageId: "" },
        sideB: raw.sideB ?? { statement: "", owner: "", sourceMessageId: "" },
        recommendedAction: raw.recommendedAction ?? "",
        eventKey: `conflict:${extractTopicWords(normalizedTopic).join(":")}`,
      });
      console.log(`[Dedup] CREATE conflict: "${raw.topic}"`);
    }
  }

  return merged;
}

// ============================================================================
// MESSAGE-LEVEL DEDUP FILTER
// ============================================================================

/**
 * Given incoming parsed messages (with contentHash already populated) and
 * the set of hashes already in the DB for this project, return only the
 * messages that are genuinely new.
 */
export function filterNewMessages(
  incoming: Array<{ contentHash?: string; id: string }>,
  existingHashes: Set<string>
): { newIndices: number[]; duplicateCount: number } {
  const newIndices: number[] = [];
  let duplicateCount = 0;
  const seenInBatch = new Set<string>();

  for (let i = 0; i < incoming.length; i++) {
    const hash = incoming[i].contentHash;
    if (!hash) {
      // No hash = can't dedup, include it
      newIndices.push(i);
      continue;
    }
    if (existingHashes.has(hash) || seenInBatch.has(hash)) {
      duplicateCount++;
    } else {
      newIndices.push(i);
      seenInBatch.add(hash);
    }
  }

  return { newIndices, duplicateCount };
}

// Re-export for convenience
export { normalizeContent };
